[package]
name = "tutorial-03"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
cloacina = { path = "../../cloacina", features = ["macros"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"
ctor = "0.2"
