/*
 *  Copyright 2025-2026 Colliery Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

//! Global computation graph registry — populated by `#[ctor]` functions
//! generated by the `#[computation_graph]` macro.
//!
//! Mirrors the global workflow/task registries used by the reconciler.

use once_cell::sync::Lazy;
use parking_lot::RwLock;
use std::collections::HashMap;
use std::sync::Arc;

use super::reactor::CompiledGraphFn;

/// Metadata about a registered computation graph.
pub struct ComputationGraphRegistration {
    /// The compiled graph function.
    pub graph_fn: CompiledGraphFn,
    /// Accumulator names declared in the graph topology.
    pub accumulator_names: Vec<String>,
    /// Reaction mode: "when_any" or "when_all".
    pub reaction_mode: String,
}

pub type ComputationGraphConstructor = Box<dyn Fn() -> ComputationGraphRegistration + Send + Sync>;
pub type GlobalComputationGraphRegistry = Arc<RwLock<HashMap<String, ComputationGraphConstructor>>>;

static GLOBAL_COMPUTATION_GRAPH_REGISTRY: Lazy<GlobalComputationGraphRegistry> =
    Lazy::new(|| Arc::new(RwLock::new(HashMap::new())));

/// Register a computation graph constructor in the global registry.
///
/// Called by `#[ctor]` functions generated by `#[computation_graph]`.
pub fn register_computation_graph_constructor<F>(graph_name: String, constructor: F)
where
    F: Fn() -> ComputationGraphRegistration + Send + Sync + 'static,
{
    let mut registry = GLOBAL_COMPUTATION_GRAPH_REGISTRY.write();
    registry.insert(graph_name.clone(), Box::new(constructor));
    tracing::debug!("Registered computation graph constructor: {}", graph_name);
}

/// Get a reference to the global computation graph registry.
pub fn global_computation_graph_registry() -> GlobalComputationGraphRegistry {
    GLOBAL_COMPUTATION_GRAPH_REGISTRY.clone()
}

/// List all registered computation graph names.
pub fn list_registered_graphs() -> Vec<String> {
    let registry = GLOBAL_COMPUTATION_GRAPH_REGISTRY.read();
    registry.keys().cloned().collect()
}

/// Remove a computation graph from the global registry.
pub fn deregister_computation_graph(graph_name: &str) {
    let mut registry = GLOBAL_COMPUTATION_GRAPH_REGISTRY.write();
    registry.remove(graph_name);
    tracing::debug!("Deregistered computation graph constructor: {}", graph_name);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::computation_graph::types::{GraphResult, InputCache};

    #[test]
    fn test_register_and_list() {
        let name = "test_graph_registry".to_string();
        register_computation_graph_constructor(name.clone(), || ComputationGraphRegistration {
            graph_fn: Arc::new(|_: InputCache| Box::pin(async { GraphResult::completed(vec![]) })),
            accumulator_names: vec!["alpha".to_string()],
            reaction_mode: "when_any".to_string(),
        });

        let names = list_registered_graphs();
        assert!(names.contains(&name));

        // Clean up
        deregister_computation_graph(&name);
    }
}
