#!/usr/bin/env python3
"""
CLOACI-T-0872 — provider release WAVE orchestration.

Providers version independently of core (ADR A-0010) and release in WAVES:
one batched ceremony covers every provider in providers/. Each wave
CLASSIFIES (bumped vs unchanged against crates.io), GUARDS candidates
(changelog entry, no path deps, publish allowed), CERTIFIES everyone
identically (the certify/ harness resolves core from crates.io and runs the
provider E2E — the compat claim is EARNED, re-earned even for unchanged
providers), PUBLISHES only the candidates, and RECORDS the tested set in
providers/COMPAT.toml.

Standalone (no angreal import) so CI workflows and the pre-commit style
guards can run it directly:

    python scripts/provider_wave.py classify [--json]
    python scripts/provider_wave.py guard <provider-dir-name>
    python scripts/provider_wave.py compat --wave <wave-id> [--certified <name>...]
    python scripts/provider_wave.py pr-check --base <git-ref>

`pr-check` is the PR guard: any provider whose src/ changed relative to
--base must carry a version bump (vs crates.io) and a matching CHANGELOG
entry — main stays self-describing so wave-day needs no archaeology.
"""

import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROVIDERS_DIR = REPO / "providers"
COMPAT = PROVIDERS_DIR / "COMPAT.toml"
UA = "cloacina-provider-wave (https://github.com/colliery-io/cloacina)"


def providers():
    """Provider crate dirs (have Cargo.toml; certify/ harnesses excluded)."""
    out = []
    for d in sorted(PROVIDERS_DIR.iterdir()):
        if d.is_dir() and (d / "Cargo.toml").exists():
            out.append(d)
    return out


def manifest_field(cargo_toml: Path, field: str):
    m = re.search(rf'^{field}\s*=\s*"([^"]+)"', cargo_toml.read_text(), re.MULTILINE)
    return m.group(1) if m else None


def crates_io_version(name: str):
    """Newest published version on crates.io, or None if never published."""
    url = f"https://crates.io/api/v1/crates/{name}"
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.load(r)
        return data["crate"]["newest_version"]
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def core_pin(cargo_toml: Path):
    """The provider's cloacina-constructor-contract pin — its certified-core claim."""
    m = re.search(
        r'^cloacina-constructor-contract\s*=\s*"=?\s*([\d.]+)"',
        cargo_toml.read_text(),
        re.MULTILINE,
    )
    return m.group(1) if m else None


def classify():
    """[(dir, name, local_version, published_version, is_candidate)]"""
    rows = []
    for d in providers():
        name = manifest_field(d / "Cargo.toml", "name")
        local = manifest_field(d / "Cargo.toml", "version")
        published = crates_io_version(name)
        rows.append((d, name, local, published, local != published))
    return rows


def guard(provider_dir: Path) -> list:
    """Candidate guards. Returns a list of failures (empty == pass)."""
    fails = []
    cargo = provider_dir / "Cargo.toml"
    text = cargo.read_text()
    version = manifest_field(cargo, "version")

    changelog = provider_dir / "CHANGELOG.md"
    if not changelog.exists():
        fails.append("no CHANGELOG.md")
    elif not re.search(rf"^##\s*\[{re.escape(version)}\]", changelog.read_text(), re.MULTILINE):
        fails.append(f"CHANGELOG.md has no entry for [{version}]")

    # Ship form: no path deps anywhere in the provider manifest.
    for m in re.finditer(r"^\s*[\w-]+\s*=\s*\{[^}]*path\s*=", text, re.MULTILINE):
        fails.append(f"path dep in Cargo.toml: {m.group(0).strip()[:60]}")

    if re.search(r"^publish\s*=\s*false", text, re.MULTILINE):
        fails.append("publish = false still set (wave prep must flip it)")

    if core_pin(cargo) is None:
        fails.append("no cloacina-constructor-contract version pin found")

    return fails


def write_compat(wave_id: str, certified: set):
    """Regenerate providers/COMPAT.toml. `certified` = provider names whose
    certify harness passed THIS wave; others keep the claim they last earned
    (their existing row is preserved with its old wave id)."""
    old = {}
    if COMPAT.exists():
        for m in re.finditer(
            r'^\[\[provider\]\]\nname = "([^"]+)"\nversion = "([^"]+)"\n'
            r'certified_core = "([^"]+)"\nwave = "([^"]+)"',
            COMPAT.read_text(),
            re.MULTILINE,
        ):
            old[m.group(1)] = (m.group(2), m.group(3), m.group(4))

    lines = [
        "# GENERATED by scripts/provider_wave.py (CLOACI-T-0872) — the tested set.",
        "# A row is a MACHINE-EARNED claim: this provider version passed its",
        "# certify/ harness (core resolved from crates.io) in the named wave.",
        "# Do not hand-edit rows; hand-edits are lies about test evidence.",
        "",
    ]
    for d in providers():
        name = manifest_field(d / "Cargo.toml", "name")
        version = manifest_field(d / "Cargo.toml", "version")
        core = core_pin(d / "Cargo.toml") or "unknown"
        if name in certified:
            row = (version, core, wave_id)
        elif name in old:
            row = old[name]
        else:
            row = (version, core, "never-certified")
        lines += [
            "[[provider]]",
            f'name = "{name}"',
            f'version = "{row[0]}"',
            f'certified_core = "{row[1]}"',
            f'wave = "{row[2]}"',
            "",
        ]
    COMPAT.write_text("\n".join(lines))
    print(f"wrote {COMPAT.relative_to(REPO)} (wave {wave_id}, certified: {sorted(certified) or '—'})")


def changed_providers(base: str):
    """Provider dirs whose src/ or Cargo.toml changed relative to `base`."""
    diff = subprocess.run(
        ["git", "diff", "--name-only", f"{base}...HEAD"],
        cwd=REPO, capture_output=True, text=True, check=True,
    ).stdout.splitlines()
    hit = set()
    for f in diff:
        m = re.match(r"providers/([^/]+)/(src/|Cargo\.toml)", f)
        if m and not f.startswith(f"providers/{m.group(1)}/certify/"):
            hit.add(m.group(1))
    return [PROVIDERS_DIR / h for h in sorted(hit) if (PROVIDERS_DIR / h / "Cargo.toml").exists()]


def cmd_classify(args) -> int:
    rows = classify()
    if args.json:
        print(json.dumps([
            {"dir": d.name, "name": name, "local": local, "published": pub, "candidate": cand}
            for d, name, local, pub, cand in rows
        ]))
        return 0
    for _d, name, local, pub, cand in rows:
        tag = "RELEASE CANDIDATE" if cand else "re-certify only"
        print(f"{name}: local {local}, published {pub or '—'} → {tag}")
    return 0


def cmd_guard(args) -> int:
    d = PROVIDERS_DIR / args.provider
    if not (d / "Cargo.toml").exists():
        print(f"no such provider: {args.provider}", file=sys.stderr)
        return 2
    fails = guard(d)
    if fails:
        for f in fails:
            print(f"✗ {args.provider}: {f}", file=sys.stderr)
        return 1
    print(f"✓ {args.provider}: guards pass")
    return 0


def cmd_compat(args) -> int:
    write_compat(args.wave, set(args.certified or []))
    return 0


def cmd_pr_check(args) -> int:
    bad = 0
    changed = changed_providers(args.base)
    if not changed:
        print("pr-check: no provider source changes")
        return 0
    for d in changed:
        name = manifest_field(d / "Cargo.toml", "name")
        local = manifest_field(d / "Cargo.toml", "version")
        published = crates_io_version(name)
        if local == published:
            print(
                f"✗ {name}: src changed but version {local} == published — "
                "bump the version and add a CHANGELOG entry "
                "(config-schema changes are breaking; see providers/PROVIDERS.md)",
                file=sys.stderr,
            )
            bad += 1
            continue
        changelog = d / "CHANGELOG.md"
        if not changelog.exists() or not re.search(
            rf"^##\s*\[{re.escape(local)}\]", changelog.read_text(), re.MULTILINE
        ):
            print(f"✗ {name}: no CHANGELOG entry for [{local}]", file=sys.stderr)
            bad += 1
        else:
            print(f"✓ {name}: {published or '—'} → {local} with changelog entry")
    return 1 if bad else 0


def main(argv) -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("classify")
    c.add_argument("--json", action="store_true")
    g = sub.add_parser("guard")
    g.add_argument("provider")
    co = sub.add_parser("compat")
    co.add_argument("--wave", required=True)
    co.add_argument("--certified", nargs="*")
    pc = sub.add_parser("pr-check")
    pc.add_argument("--base", required=True)
    args = ap.parse_args(argv)
    return {"classify": cmd_classify, "guard": cmd_guard,
            "compat": cmd_compat, "pr-check": cmd_pr_check}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
