---
name: Cloacina-CTL Tests

on:
  workflow_call:  # Only called by ci.yml

concurrency:
  group: cloacina-ctl-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloacina-ctl-tests:
    name: Cloacina-CTL Tests
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, integration]
        backend: [postgres, sqlite]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cloacina-ctl-${{ matrix.backend }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cloacina-ctl-${{ matrix.backend }}-
            ${{ runner.os }}-cloacina-ctl-

      - name: Docker Compose Cache
        if: matrix.backend == 'postgres'
        uses: actions/cache@v4
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('.angreal/docker-compose.yaml') }}

      - name: Start PostgreSQL services
        if: matrix.backend == 'postgres'
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".angreal/docker-compose.yaml"

      - name: Run ${{ matrix.test-type }} tests (${{ matrix.backend }})
        run: angreal ctl ${{ matrix.test-type }} --backend ${{ matrix.backend }}
