---
name: Examples & Documentation

on:
  workflow_call:  # Called by ci.yml
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: examples-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tutorials:
    name: Tutorial Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-tutorials-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-tutorials-
            ${{ runner.os }}-rust-

      - name: Run tutorial tests
        run: angreal cloacina tutorial

  examples:
    name: Example Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-examples-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-examples-
            ${{ runner.os }}-rust-

      - name: Run example tests
        run: angreal cloacina example

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-docs-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-docs-
            ${{ runner.os }}-rust-

      - name: Build documentation
        run: angreal cloacina docs

  python-tutorials:
    name: Python Tutorial Tests
    strategy:
      fail-fast: false
      matrix:
        backend: [postgres, sqlite]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-py-tutorials-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-py-tutorials-
            ${{ runner.os }}-cargo-

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Run Python tutorial tests
        run: |
          angreal cloaca tutorial --backend ${{ matrix.backend }}
