---
name: Examples & Documentation

on:
  workflow_call:  # Only called by ci.yml

concurrency:
  group: examples-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tutorials:
    name: Tutorial Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-tutorials-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-tutorials-
            ${{ runner.os }}-rust-

      - name: Run tutorial tests
        run: angreal tutorials all

  examples:
    name: Example Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-examples-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-examples-
            ${{ runner.os }}-rust-

      - name: Docker Compose Cache
        uses: actions/cache@v4
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('.angreal/docker-compose.yaml') }}

      - name: Start PostgreSQL services
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".angreal/docker-compose.yaml"

      - name: Run example tests
        run: |
          angreal examples cron-scheduling
          angreal examples multi-tenant
          angreal examples per-tenant-credentials

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-docs-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-docs-
            ${{ runner.os }}-rust-

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build documentation
        run: angreal docs build

  python-tutorials:
    name: Python Tutorial Tests
    strategy:
      fail-fast: false
      matrix:
        backend: [postgres, sqlite]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-py-tutorials-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-py-tutorials-
            ${{ runner.os }}-cargo-

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Docker Compose Cache
        if: matrix.backend == 'postgres'
        uses: actions/cache@v4
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('.angreal/docker-compose.yaml') }}

      - name: Start PostgreSQL services
        if: matrix.backend == 'postgres'
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".angreal/docker-compose.yaml"

      - name: Run Python tutorial tests
        run: |
          angreal cloaca tutorial --backend ${{ matrix.backend }}
