---
name: Performance Tests

on:
  workflow_call:  # Only called by ci.yml
  workflow_dispatch:  # Allow manual triggering

concurrency:
  group: performance-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  performance-tests:
    name: Performance Tests
    strategy:
      fail-fast: false
      matrix:
        test-type: [simple, pipeline, parallel]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-performance-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-performance-
            ${{ runner.os }}-rust-

      - name: Run ${{ matrix.test-type }} performance test
        run: angreal performance ${{ matrix.test-type }}

  performance-quick:
    name: Quick Performance Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-performance-quick-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-performance-
            ${{ runner.os }}-rust-

      - name: Run quick performance test
        run: angreal performance quick
