---
name: Python Tutorials
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  python-tutorials:
    name: Python Tutorials
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        backend: [postgres, sqlite]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-tutorials-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-tutorials-
            ${{ runner.os }}-cargo-

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Run Python tutorials for ${{ matrix.backend }}
        run: |
          # Run all tutorials appropriate for this backend
          # SQLite: tutorials 1-4, PostgreSQL: tutorials 1-5
          angreal cloaca tutorial --backend ${{ matrix.backend }}

      - name: Verify tutorial outputs
        run: |
          # Check that tutorial database files were created (for SQLite)
          if [ "${{ matrix.backend }}" = "sqlite" ]; then
            echo "Checking for tutorial database files..."
            ls -la python_tutorial_*.db* || echo "No tutorial databases found (this is normal after cleanup)"
          fi

          echo "✓ Tutorial verification completed"
