---
name: Rust Tests

on:
  workflow_call:  # Called by ci.yml
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: rust-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-tests:
    name: Rust Tests
    strategy:
      fail-fast: false
      matrix:
        test-type: [unit, integration, macro]
        backend: [postgres, sqlite]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ matrix.backend }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ matrix.backend }}-
            ${{ runner.os }}-rust-

      - name: Run ${{ matrix.test-type }} tests (${{ matrix.backend }})
        run: angreal cloacina ${{ matrix.test-type }} --backend ${{ matrix.backend }}

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-smoke-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-smoke-
            ${{ runner.os }}-rust-

      - name: Run smoke tests
        run: angreal cloacina smoke
